#
# Essentials plugin configuration.
# The database connection details are stored according to the shared-connections configuration specification inside the "connections.json"
#
_version: 2
chat:
  format: "%luckperms_prefix% %player_name% <dark_gray>➥ <gray><message>" # <message> interne Variable. % % gehören zur Placeholder API
  private:
    sender: "<white>Du <dark_gray>➥ <gray><receiver> <gray><message>"
    receiver: "<gray><sender> <dark_gray>➥ <white>Dich <gray><message>"
plots-cmd-proxy:
  enabled: true
  server: "citybuild"
# '|' is used to indicate a multi-line string in YAML
info-message: |
  <prefix> <p>Feli hat die config.yml von Essentials nicht angepasst.  
  <prefix> <gray>Viel Spaß beim Spielen!
broadcast:
  broadcasts:
    broadcast1:
      enabled: true
      interval-seconds: 120
      messages:
        - "<prefix> <p>Willkommen auf dem Server!"
        - "<prefix> <p>Besuche unseren Discord: <hl>discord.example</hl>"
    broadcast2:
      enabled: true
      interval-seconds: 300
      messages:
        - "<prefix> <p>Regeln: /rules"
